# ==========================================================
# TAT-MNAT ARCHITECTURE CONFIGURATION
# ==========================================================

data:
  # Explicitly list the sequences to evaluate
  eval_sequences:
    - "data/MOT17/train/MOT17-02-FRCNN"
    - "data/MOT17/train/MOT17-02-FRCNN-Whitebox"
    - "data/MOT17/train/MOT17-02-FRCNN-Blackbox"
    - "data/MOT17/train/MOT17-04-FRCNN"
    - "data/MOT17/train/MOT17-04-FRCNN-Whitebox"
    - "data/MOT17/train/MOT17-04-FRCNN-Blackbox"
    - "data/MOT17/train/MOT17-09-FRCNN"
    - "data/MOT17/train/MOT17-09-FRCNN-Whitebox"
    - "data/MOT17/train/MOT17-09-FRCNN-Blackbox"
    - "data/MOT17/train/MOT17-10-FRCNN"
    - "data/MOT17/train/MOT17-10-FRCNN-Whitebox"
    - "data/MOT17/train/MOT17-10-FRCNN-Blackbox"
    - "data/MOT17/train/MOT17-13-FRCNN"
    - "data/MOT17/train/MOT17-13-FRCNN-Whitebox"
    - "data/MOT17/train/MOT17-13-FRCNN-Blackbox"


paths:
  weights_out: "weights/tat_hardened_mnat_epoch_10.pth"
  figures_out: "outputs/figures/"
  trackeval_out: "TrackEval/data/trackers/mot_challenge/MOT17-train/"

training:
  batch_size: 4
  num_epochs: 10
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005

adversarial_bounds:
  L_inf: 0.03137
  L_2: 1.5
  L_1: 0.1
  L_1_sparsity: 0.05

system:
  device: "cuda"
  num_workers: 4