# config.yaml — PHASE 2: TARGET DISCRIMINATION

data:
  seq_path: data/MOT17/train/MOT17-04-FRCNN

  train_sequences:
    - data/MOT17/train/MOT17-02-FRCNN-Whitebox  # POISONED
    - data/MOT17/train/MOT17-04-FRCNN-Whitebox  # POISONED
    - data/MOT17/train/MOT17-09-FRCNN-Whitebox  # POISONED

reward:
  w_rec:  5.0       
  w_fp:   5.0       
  w_lost: 0.5       
  w_cost: 0.0       

ppo:
  total_timesteps: 100000 
  n_steps: 512
  batch_size: 128
  n_epochs: 10
  learning_rate: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  initial_ent_coef: 0.08  # The initial shock to break the paralysis
  final_ent_coef: 0.001   # The final convergence value
  net_arch: [128, 128]

paths:
  model_load: outputs/mtd_ppo_agent_phase3  # The brain we are starting with
  model_save: outputs/mtd_ppo_agent_phase4  # The new brain we are forging
  tb_logs: outputs/tb_logs

device:
  use_gpu: true
  gpu_id: 0
  n_envs: 1         # MUST STAY 1 FOR 8GB VRAM                                        